src/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("", views.home, name="home"),
    path("upload_excel/", views.upload_excel, name="upload_excel"),
]

src/project_settings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("products.urls")),
]

src/parsers/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(verbose_name="Название товара", max_length=250)
    sku = models.IntegerField(db_index=True, verbose_name="SKU товара")
    root = models.IntegerField(verbose_name="Id источника отзывов")
    rating = models.FloatField(verbose_name="Текущий рейтинг")

    # @property
    # def rating(self):
    #     feedbacks = self.feedbacks.all()
    #     total_summ = 0
    #     for feedback in feedbacks:
    #         total_summ += feedback.buyer_rating
    #     return round(total_summ/len(feedbacks), 1)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class Feedback(models.Model):
    buyer_name = models.CharField(verbose_name="Имя покупателя", max_length=50)
    buyer_id = models.IntegerField(verbose_name="ID покупателя")
    source_id = models.CharField(
        db_index=True, verbose_name="Id отзыва на источнике", max_length=50
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="feedbacks",
        verbose_name="Товар",
    )
    text = models.TextField(
        verbose_name="Отзыв",
    )
    buyer_rating = models.IntegerField(verbose_name="Оценка покупателя")
    created = models.DateTimeField(
        verbose_name="Дата создания отзыва", auto_now=False, auto_now_add=True
    )

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"

src/products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(verbose_name="Название товара", max_length=250)
    sku = models.IntegerField(db_index=True, verbose_name="SKU товара")
    root = models.IntegerField(verbose_name="Id источника отзывов")
    rating = models.FloatField(verbose_name="Текущий рейтинг")

    # @property
    # def rating(self):
    #     feedbacks = self.feedbacks.all()
    #     total_summ = 0
    #     for feedback in feedbacks:
    #         total_summ += feedback.buyer_rating
    #     return round(total_summ/len(feedbacks), 1)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class Feedback(models.Model):
    buyer_name = models.CharField(verbose_name="Имя покупателя", max_length=50)
    buyer_id = models.IntegerField(verbose_name="ID покупателя")
    source_id = models.CharField(
        db_index=True, verbose_name="Id отзыва на источнике", max_length=50
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="feedbacks",
        verbose_name="Товар",
    )
    text = models.TextField(
        verbose_name="Отзыв",
    )
    buyer_rating = models.IntegerField(verbose_name="Оценка покупателя")
    created = models.DateTimeField(
        verbose_name="Дата создания отзыва", auto_now=False, auto_now_add=True
    )

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

src/products/views.py
import openpyxl

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages

from products.parsers import parse_product
from products.models import Product


def home(request):
    products = Product.objects.all().order_by("sku")
    context = {
        "products": products,
    }
    return render(request, "products/index.html", context=context)


def upload_excel(request):
    data = {}
    if "GET" == request.method:
        return render(request, "products/upload.html", data)

    try:
        excel_file = request.FILES["excel_file"]
        if not excel_file.name.endswith(".xlsx"):
            messages.error(request, "File is not a XLSX")
            return HttpResponseRedirect(reverse("products:upload_excel"))
        if excel_file.multiple_chunks():
            messages.error(
                request,
                "Uploaded file is too big (%.2f MB). "
                % (excel_file.size / (1000 * 1000),),
            )
            return HttpResponseRedirect(reverse("products:upload_excel"))
        file_data = openpyxl.load_workbook(excel_file)
        worksheet = file_data["Лист1"]
        errors = False
        for row in worksheet.iter_rows():
            for cell in row:
                try:
                    parse_product(int(cell.value))
                except Exception as e:
                    messages.error(request, "Unable to upload file. " + repr(e))
                    errors = True
                    pass
        if not errors:
            messages.success(request, "All data uploaded successfully!")
    except Exception as e:
        messages.error(request, "Unable to upload file. " + repr(e))
    return HttpResponseRedirect(reverse("products:upload_excel"))

src/products/templates/products/index.html
<!DOCTYPE html>
<html lang="ru">

<head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.2.0/css/all.min.css" integrity="sha512-6c4nX2tn5KbzeBJo9Ywpa0Gkt+mzCzJBrE1RB6fmpcsoN+b/w/euwIMuQKNyUoU/nToKN3a8SgNOtPrbW12fug==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <!--Fonts-->
    <title>
      {% block title %}Рассылка негативных отзывов{% endblock %}
    </title>
</head>
<body>
    <div class="main">
        <div class="container">
          <div class="row">
            <div class="text-center">
                {% block content %}
                
                <div style="margin: 50px 50px 50px 50px;">
                  <h2>
                    Рассылка негативных отзывов (таблица товаров)
                  </h2>
                  <ul>
                  
                  <table class="table table-striped table-hover">
                      <thead>
                          <tr>
                            <th scope="col">№</th>
                            <th scope="col">sku</th>
                            <th scope="col">Наименование</th>
                            <th scope="col">Рейтинг</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for product in products %}
                          <tr>
                            <th scope="row">{{forloop.counter}}.</th>
                            <td>
                              <h5 class="card-title">{{ product.sku }}</h5>
                            </td>
                            <td>
                              <h5 class="card-title">{{ product.name }}</h5>
                            </td>
                            <td>
                              <h5 class="card-title">{{ product.rating }}</h5>
                            </td>
                          </tr>
                          {% endfor %}
                  </table>
                  
                  <br>
                    <a href="{% url 'products:upload_excel' %}" class="btn btn-sm btn-success"> Добавить sku </a>
                  </ul>
              </div>
                {% endblock %}
            </div>
          </div>
        </div>
    </div>
</body>
</html>

src/products/templates/products/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload</title>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <br>
    <h2 style="text-align: center;">For upload xlsx-file</h2>
    <form action="{% url "products:upload_excel" %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
            <div class="col-md-8">
                <input type="file" name="excel_file" id="excel_file" required="True" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
                 <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
                 <a href="{% url 'products:home' %}" class="btn btn-sm btn-success"> Назад </a>
            </div>
        </div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </form>
</body>
</html>